//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Detail { get; set; }
        public Nullable<int> IsReply { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RepliedBy { get; set; }
        public Nullable<System.DateTime> RepliedDate { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
